### ISSUE TITLE
EntityFramework6.Npgsql update to use Npgsql 4.1?

### ISSUE THREAD

**Issue by warcha** [npgsql/EntityFramework6.Npgsql#137]
Hi I tried updating the latest release of EF6.Npgsql (3.2.1) to use Npgsql (4.1) by changing the TargetFramework to net461 and changing the reference to Npgsql (4.0.7) to point to Npgsql (4.1) however when running the test suite I get the following error:

_System.InvalidOperationException: This NpgsqlTransaction has completed; it is no longer usable._

which looks to be directly related to: https://github.com/npgsql/npgsql/issues/985. The last comment on there was that the IsCompleted flag was being removed for Npgsql 4.1.

Does this mean that the EF6.Npgsql (3.2.1) project needs to be updated to use Npgsql 4.1 and if so what kind of time frame could this be expected to be completed in?

**Comment by ntuchenxy** [comment]
same problem, now i put all database related codes in a TransactionScope as a temporary solution.

**Comment by daboss84** [comment]
Same here. I started on Friday with an EF6/Postgres Project. I am always getting this execption during Migration, during Save(), ... (At first, I ignored it, because, e.g. Save() got executed in the "real" database, but today I realized I can't even run the Migrations properly)

@warcha which configration was your last working one? (Which versions did you use?)

My current packages:
EntityFramework 6.3.0
EntityFramework6.Npgsql 6.3.0-preview5 (did not work with last stable 3.2.1.1 either)
Npgsql 4.1.0

**Comment by busyscout** [comment]
Same problem. 4.0.10 works, 4.1 gives an error.

**Comment by roji** [comment]
Thanks to everyone for the testing the new version!

First, Npgsql 4.1.0 contained a few unintended breaking changes. 4.1.1 will be released very soon (i.e. a couple days) and should fix these.

Second, I also need to publish version 6.3.0 of the EF6 provider - this will probably have to wait a few extra days but it will happen soon as well. That would be the right version to test rather than preview5.

**Comment by arif-hanif** [comment]
I am looking forward to EF 6.3, currently have had to use join tables for many to many fields in EF Core any timeline on this?

**Comment by roji** [comment]
Just published 6.3.0 to nuget.org! Please try it out and let me know how it works!

**Comment by roji** [comment]
Note that the new version uses 4.0.10 by default, in order to preserve compatibility with .NET Framework 4.5. However, you can take a dependency on Npgsql 4.1 instead.

**Comment by rtibbett** [comment]
I was also getting the same error ' This NpgsqlTransaction has completed; it is no longer usable' using .net 4.7.1, EF 6.3.0, EF6.Npgsql 6.3.0 and Npgsql 4.1.0. Good news Npgsql 4.1.1 fixed the problem for me. Wasted so much time on this!

**Comment by roji** [comment]
Good to hear this is working again and sorry for the trouble.
