### ISSUE TITLE
JetBrains.Annotations missing as dependencie

### ISSUE THREAD

**Issue by jasperspahl** [npgsql/EntityFramework6.Npgsql#183]
when trying to use EntityFramework6.Npgsql with Npgsql v6.0.3 the program won't work because JetBrains.Annotations isn't loaded as a dependencie

**Comment by roji** [comment]
@jasperspahl you seem to be trying to run the non-Core EF6 provider (e.g. version [6.4.3](https://www.nuget.org/packages/EntityFramework6.Npgsql/6.4.3)) against a version of Npgsql that's newer than what it was compiled against - this is not supported. EntityFramework6.Npgsql 6.4.3 was compiled against Npgsql 4.1, you'll have to stick with that. 

It may be possible to build recompile EntityFramework6.Npgsql against Npgsql 6 and to make it work, but this is likely a non-trivial thing... Note also that the non-Core EF6 provider is archived, and isn't really being maintained any more. I'd recommend looking at upgrading to EF Core; otherwise, I'd stay with the versions which work.
