### ISSUE TITLE
nuspec needs to be updated to be usable with npgsql >= 3.1.5 (package casing change) for .net core projects

### ISSUE THREAD

**Issue by rwasef1830** [npgsql/EntityFramework6.Npgsql#39]
Hello,
Since npgsql 3.1.5, the nuget package name changed from "Npgsql" to "npgsql". It seems that dotnet package restore treats package names as case sensitive whereas the old csproj system nuget is case-insensitive with regards to package name / dependency resolution.

In a normal csproj project, using the latest release of this project with npgsql 3.1.5 works fine, but when trying to add npgsql 3.1.5 with EntityFramework6.Npgsql latest in project.json, dotnet fails with "Cannot resolve Npgsql >= 3.1.0" and the project cannot compile.

@roji @Emill

**Comment by borgdylan** [comment]
This issue is also present when using EF6 on Mono.

**Comment by borgdylan** [comment]
@rwasef1830 Not only did the package name change, but also the assembly name.

**Comment by rwasef1830** [comment]
@borgdylan I think Nuget handles adding the updated assembly name correctly because nuspec specifies dependency to package, not to the assembly directly. The npgsql package should handle specifying its own assemblies and I'm assuming it's specified correctly in its own nuspec file.

**Comment by roji** [comment]
@rwasef1830, @borgdylan, sorry about this. I built 3.1.5 on my local machine because the build server is having issues. `dotnet cli` infers the project name from the directory, but unfortunately in Windows you can cd into npgsql or Npgsql, and that will actually change the package ID in the nuspec etc. So annoying.

I think the best way forward is will simply be to release 3.1.6 as before, with Npgsql instead of npgsql - this way things go back to the way they were. In the meantime, if you urgently need 3.1.5 you can simply create a 3.1.5.1 yourself with the proper casing...

Will close this but feel free to post if you think something else should be done etc.

**Comment by roji** [comment]
Npgsql issue reminder: https://github.com/npgsql/npgsql/issues/1185

**Comment by borgdylan** [comment]
@roji Thanks I just needed an up to date version that does not print the connection string password on the console.

**Comment by roji** [comment]
@borgdylan in that case use 3.1.4 for now, I'll probably release 3.1.6 in a couple of weeks or so

**Comment by matthewjcooper** [comment]
I'm confused on how i'm supposed to resolve this. I'm using your entityframeworkcore libraries and am getting :

Could not load file or assembly 'npgsql, Version=3.1.5.0, 

i have these lines in my project.json dependencies:

    "Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0",
    "Npgsql.EntityFrameworkCore.PostgreSQL.Design": "1.0.0",
    "Npgsql" : "3.1.5",

Changing to 3.1.4 causes errors since 1.0.0 of the entityframework libraries relies on 3.1.5

What is the recommended resolution for my situation?

**Comment by roji** [comment]
@matthewjcooper, just try removing the Npgsql dependency from your project.json, Npgsql.EntityFrameworkCore.PostgreSQL will automatically pull in the right version anyway. The next version of Npgsql and Npgsql.EntityFrameworkCore.PostgreSQL will fix all this.
