### ISSUE TITLE
Dependency mismatch between nuget and assembly

### ISSUE THREAD

**Issue by roji** [npgsql/EntityFramework6.Npgsql#43]
Although the EF6.Npgsql 3.1.1 nuspec specifies Npgsql 3.1.0 as a dependency, the EntityFramework6.Npgsql DLL itself depends on Npgsql 3.1.2.

**Comment by edumartins7** [comment]
A 3.1.2 version containing this fix (perhaps only containing this fix) would be much welcomed, since the latest package available at Nuget still is the 3.1.1. Every now and then I end up facing [issues like this one](https://stackoverflow.com/questions/38378741/incompatible-versions-of-npgsql-and-entityframework6-npgsql), I think more people face it too. Now I solve it faster but at the first time it happed it took me quite a few hours.

**Comment by roji** [comment]
I've neglected EF6.Npgsql, a new package should have been released a long time ago. I'll really make an effort to do that this weekend.

**Comment by roji** [comment]
I've transitioned the project to use the new csproj, where this kind of issue is no longer necessary (all dependency management is in the csproj). Version 3.2.0 should be released in the next day or two.
