### ISSUE TITLE
EF6 + Client Cert Auth (ProvideClientCertificatesCallback)

### ISSUE THREAD

**Issue by syserr0r** [npgsql/EntityFramework6.Npgsql#59]
I am new to EF6 and trying to implement the `ProvideClientCertificatesCallback` so as to use certificate based authentication.

I have (barely) managed to get EF6 to use my custom `IDbConnectionFactory` but it seems to require hard-cording the connection string (as the default is only called if the connection string isn't specified, and my attempts at overriding with DbConfiguration.Loaded seem not to work).

Even so, the callback never seems to be called.
```c#
public class clientCertFactory: IDbConnectionFactory
{
	internal string _clientCertPath = "";

	public DbConnection CreateConnection(string nameOrConnectionString)
	{
		var c = new NpgsqlConnection("SSL Mode=Require;Username=xxx;Host=yyy;Database=zzz");
		if (ConfigurationManager.AppSettings.Get("clientCert") != null)
		{
			_clientCertPath = ConfigurationManager.AppSettings.Get("clientCert");
			/*c.ProvideClientCertificatesCallback += new ProvideClientCertificatesCallback((X509CertificateCollection clientCerts) => {
				X509Certificate2 cert = new X509Certificate2(_clientCertPath);
				clientCerts.Add(cert);
			});*/

			c.ProvideClientCertificatesCallback += new ProvideClientCertificatesCallback(ProvideClientCertificates);
		}
		return c;
	}

	internal void ProvideClientCertificates(X509CertificateCollection clientCerts)
	{
		System.Console.WriteLine(String.Format("Attempting to apply cert: {0}", _clientCertPath));
		X509Certificate2 cert = new X509Certificate2(_clientCertPath);
		clientCerts.Add(cert);
	}
}
```

Is client cert auth supported by EF6.Npgsql and if so, what is the recommended way of implementing it?

**Comment by syserr0r** [comment]
After some further digging it appears the problem lies in the `UsingPostgresDbConnection` function in [`NpgsqlServices.cs`](https://github.com/npgsql/EntityFramework6.Npgsql/blob/dev/src/EntityFramework6.Npgsql/NpgsqlServices.cs#L178).

In that function a new connection is created using the existing connection's connectionstring; therefore not having the client certificates needed to authenticate and failing/throwing an exception.

I'm not entirely sure if there is a reason to spin a new separate connection up for these commands but I will try building a version where it does not to see if I can progress further.

**Comment by roji** [comment]
Thanks for looking into this @syserr0r...

`UsingPostgresDbConnection` is used for administrative operations such as creating or deleting a database. Especially for creating a database, this is necessary since there's a chicken-and-egg problem - you want to create a database but can't connect yet because it doesn't exist. So we connect to an administrative database instead (`template1` by default, but changeable via `EntityAdminDatabase`).

However, you're correct that currently `UsingPostgresDbConnection` has an issue - it simply duplicates the user's connection string and changes the database, which leaves out SSL settings. The correct way to do this would be to call `NpgsqlConnection.CloneWith()` on the user's connection. This will create a new connection with the given connection string (so to the administrative database), and then copy across *all* authentication info from the user's connection.

If you'd like to send a PR I'll merge it, otherwise let me know and I'll make the change.

**Comment by sgrinko** [comment]
I have similar problems.
Pgbouncer has no access to the template1 database. Therefore, an attempt to connect to an existing database crashes!
What it means: but changeable via EntityAdminDatabase
Is this indicated in the connection string?
Can I have an example?
